window.g_tabFiles = [
  { band: "AC-DC", tabs: [
    "Ain't No Fun.gp4",
    "All Screwed Up.gp3",
    "Are you ready.gp5",
    "Baby Please Don't Go.gp3",
    "Back In Black.gp3",
    "Bad Boy Boogie.gp4",
    "Ballbreaker.gp4",
    "Beating Around The Bush.gp4",
    "Big Balls.gp3",
    "Big Gun.gp3",
    "Bonny.gp3",
    "Burnin' Alive.gp3",
    "C.O.D..gp4",
    "Can't Stand Still.gp4",
    "Can't Stop Rock N' Roll.gp4",
    "Come And Get It.gp4",
    "Cover You In Oil.gp4",
    "D.T.gp4",
    "Damned.gp3",
    "Dirty Deeds Done Dirt Cheap.gp4",
    "Dog eat dog.gp3",
    "Flick Of The Switch.gp4",
    "Fling Thing.gp4",
    "Fly On The Wall.gp4",
    "For Those About To Rock.gp3",
    "Gimme A Bullet.gp4",
    "Girls got rhythm.gp3",
    "Hail Caesar.gp3",
    "Hard As A Rock.gp3",
    "Have A Drink On Me.gp3",
    "Heatseeker.gp4",
    "Hell Aint A Bad Place To Be.gp3",
    "Hells Bells.gp4",
    "High Voltage.gp3",
    "Highway to Hell.gp3",
    "If You Want Blood.gp4",
    "Inject The Venom.gp4",
    "It's A Long Way To The Top.gp4",
    "Jailbreak.gp4",
    "Let Me Put My Love Into You.gp3",
    "Let me put my love.gp3",
    "Let There Be Rock.gp3",
    "Let's Get It Up.gp4",
    "Little Lover.gp3",
    "Love Bomb.gp3",
    "Meanstreak.gp4",
    "Meltdown.gp3",
    "Mix ACDC.gp3",
    "Moneytalks.gp4",
    "Nervous Shakedown.gp4",
    "Night Of The Long Knives.gp4",
    "Overdose.gp4",
    "Problem Child.gp4",
    "Ride On.gp4",
    "Riff Raff.gp4",
    "Rock And Roll Ain't Noise Pollution.gp3",
    "Rock and Roll Damnation.gp3",
    "Rock'n'Roll Singer.gp3",
    "Rocker.gp3",
    "Safe In New York City.gp3",
    "Sattelite Blues.gp3",
    "Shoot To Thrill.gp3",
    "Shot Down In Flames.gp4",
    "Sin City.gp3",
    "Sink The Pink.gp4",
    "Squealer.gp3",
    "Stiff Upper Lip.gp3",
    "The Furor.gp3",
    "The Jack.gp4",
    "The Razors Edge.gp3",
    "Thunderstruck.gp4",
    "TNT.gp4",
    "Touch Too Much.gp4",
    "Walk All Over You.gp4",
    "What Do You Do For Money Honey.gp4",
    "Who Made Who.gp4",
    "Whole Lotta Rosie.gp4",
    "You Ain't Got A Hold On Me.gp3",
    "You Shook Me All Night Long.gp4"
  ] },
  { band: "Accept", tabs: [
    "Aiming High.gp4",
    "All Or Nothing.gp4",
    "Amamos La Vida.gp4",
    "Another Second To Be.gp4",
    "Balls To the Wall.gp3",
    "Bound To Fail.gp4",
    "Breaker.gp4",
    "Bulletproof.gp4",
    "Burning.gp4",
    "Can't Stand The Night.gp4",
    "China Lady.gp4",
    "Don't Go Stealing My Soul Away.gp4",
    "Donation.gp4",
    "Fast as a shark.gp3",
    "Flash Rocking Man.gp4",
    "Guardian Of The Night.gp4",
    "Head Over Heels.gp4",
    "Hellhammer.gp4",
    "I Don't Wanna Be Like You.gp4",
    "I Wanna Be No Hero.gp4",
    "I'm A Rebel.gp4",
    "Just By My Own.gp3",
    "Living For Tonight.gp4",
    "London Leatherboys.gp4",
    "Losers And Winners.gp4",
    "Losing More Than You Ever Had.gp4",
    "Love Child.gp4",
    "Love Sensation.gp4",
    "Metal Heart.gp4",
    "Midnight Highway.gp4",
    "Midnight Mover.gp4",
    "Monsterman.gp4",
    "Neon Nights.gp4",
    "Objection Overruled.gp3",
    "Pomp And Circumstance.gp4",
    "Princess Of The Dawn.gp4",
    "Prisoner.gp4",
    "Restless And Wild.gp4",
    "Run If You Can.gp4",
    "Russian Roulette.gp4",
    "Save Us.gp4",
    "Screaming For A Love-bite.gp4",
    "Shake Your Heads.gp4",
    "Sick, Dirty & Mean.gp4",
    "Slaves To Metal.gp4",
    "Son Of A Bitch.gp4",
    "Stand Tight.gp4",
    "Starlight.gp4",
    "T.V. War.gp4",
    "The King.gp3",
    "Thunder And Lightning.gp4",
    "Turn Me On.gp4",
    "Up To The Limit.gp4",
    "Walking In The Shadow.gp4",
    "Winter Dreams.gp4"
  ] },
  { band: "Aerosmith", tabs: [
    "Ain't That A Bitch.gp3",
    "Amazing.gp3",
    "Attitude Adjustment.gp3",
    "Avant Garden.gp3",
    "Baby, Please Don't Go.gp3",
    "Crazy.gp3",
    "Cryin'.gp3",
    "Don't Get Mad, Get Even.gp4",
    "Dream On.gp4",
    "Dude Looks Like A Lady.gp3",
    "Dulcimer Stomp.gp4",
    "Eat the Rich.gp3",
    "Falling in Love.gp3",
    "Get A Grip.gp4",
    "Girls Of Summer.gp3",
    "Hole In My Soul.gp4",
    "I Don't Want To Miss A Thing.gp3",
    "I live in Connecticut.gp3",
    "I'm down.gp3",
    "Jaded.gp3",
    "Janie's Got A Gun.gp3",
    "Kings And Queens.gp3",
    "Last Child.gp3",
    "Lay It Down.gp4",
    "Light Inside.gp3",
    "Livin' on the Edge.gp3",
    "Lord of the Thighs.gp3",
    "Mama Kin.gp4",
    "Movin' Out.gp3",
    "Nine Lives.gp3",
    "No More No More.gp3",
    "Pink.gp3",
    "Rag Doll.gp3",
    "Road Runner.gp4",
    "Same Old Song And Dance.gp3",
    "Seasons Of Wither.gp4",
    "Shut Up And Dance.gp4",
    "Subway.gp3",
    "Sunshine.gp3",
    "Sweet Emotion.gp3",
    "Taste Of India.gp3",
    "The Farm.gp3",
    "The Grind.gp3",
    "Train Kept A Rollin.gp4",
    "Trip Hoppin'.gp3",
    "Walk On Down.gp4",
    "Walk This Way.gp4",
    "What it takes.gp3"
  ] },
  { band: "Alice Cooper", tabs: [
    "Aspirin Damage.gp4",
    "Ballad of the dwight frye.gp3",
    "Bed Of Nails.gp4",
    "Billion Dollar Babies.gp4",
    "Brutal Planet.gp3",
    "Clones.gp4",
    "Dangerous Tonight.gp4",
    "Dead Babies.gp3",
    "Desperado.gp4",
    "Gimme.gp3",
    "I'm Eighteen.gp3",
    "Muscle Of Love.gp4",
    "No More Mr. Nice Guy.gp4",
    "Pick Up The Bones.gp4",
    "Poison.gp4",
    "Schools Out.gp4",
    "Snakebite.gp4",
    "Take It Like A Woman.gp4",
    "Wicked Young Man.gp3"
  ] },
  { band: "Anthrax", tabs: [
    "Antisocial.gp3",
    "Black Lodge.gp4",
    "Caught in A Mosh.gp3",
    "Crush.gp4",
    "Deathrider.gp4",
    "Got The Time.gp4",
    "Gung Ho.gp4",
    "I Am The Law.gp4",
    "Imitation Of Life.gp4",
    "Indians.gp4",
    "Inside Out.gp3",
    "Madhouse.gp4",
    "Medusa.gp4",
    "Metal Thrashing Mad.gp4",
    "Only.gp3",
    "Panic.gp3",
    "Random Acts Of Senseless Violence.gp3",
    "Refuse To Be Denied.gp4",
    "Room For One More.gp4",
    "Safe Home.gp4",
    "Skeletons In The Closet.gp3",
    "Taking The Music Back.gp4",
    "What Doesn't Die.gp4"
  ] },
  { band: "Avenged Sevenfold", tabs: [
    "And All Things Will End.gp4",
    "Bat Country.gp4",
    "Beast And The Harlot.gp4",
    "Breaking Their Hold.gp4",
    "Burn It Down.gp4",
    "Chapter Four.gp4",
    "Clairvoyant Disease.gp4",
    "Darkness Surrounding.gp4",
    "Desecrate Through Reverance.gp4",
    "Eternal Rest.gp4",
    "M.i.a..gp4",
    "Radiant Eclipse.gp4",
    "Remenissions.gp4",
    "Second Heartbeat.gp4",
    "Seize The Day.gp4",
    "Sidewinder.gp4",
    "Streets.gp4",
    "Strength Of The World.gp4",
    "The Wicked End.gp4",
    "To End The Rapture.gp4",
    "Trashed And Scattered.gp4",
    "Turn The Other Way.gp4",
    "Unholy Confessions.gp4",
    "Warmness On The Soul.gp4"
  ] },
  { band: "Bad Company", tabs: [
    "Bad Company.gp4",
    "Cant Get Enough.gp3",
    "Feel's Like Makin' Love.gp3",
    "Rock Steady.gp4",
    "Wishing Well.gp4"
  ] },
  { band: "Black Sabbath", tabs: [
    "A Hard Road.gp3",
    "A National Acrobat.gp4",
    "After All.gp4",
    "After forever.gp3",
    "Angry Heart.gp4",
    "Anno Mundi.gp4",
    "Behind the Wall of Sleep.gp3",
    "Black Sabbath.gp4",
    "Changes.gp3",
    "Children Of The Grave.gp4",
    "Children Of The Sea.gp3",
    "Cornucopia.gp3",
    "Country Girl.gp3",
    "Demonoid Phenomenon.gp4",
    "Die Young.gp4",
    "Dirty Women.gp3",
    "Dying For Love.gp4",
    "Electric Funeral.gp4",
    "Evil Woman.gp3",
    "Fairies Wear Boots.gp3",
    "Fine.gp4",
    "Fluff.gp3",
    "Hand Of Doom.gp4",
    "Headless Cross.gp4",
    "Heaven and Hell.gp4",
    "Hole in the Sky.gp3",
    "I Won't Cry For You.gp3",
    "I.gp4",
    "In Memory.gp4",
    "Into The Void.gp4",
    "Iron Man.gp3",
    "Killing Yourself To Live.gp4",
    "Laguna Sunrise.gp3",
    "Lonely Is The World.gp4",
    "Lord of this World.gp3",
    "N.I.B..gp3",
    "Neon Knights.gp3",
    "Orchid.gp3",
    "Paranoid.gp3",
    "Planet Caravan.gp3",
    "Psycho Man.gp3",
    "Rat Salad.gp3",
    "Sabbath Bloody Sabbath.gp4",
    "Selling My Soul.gp3",
    "She's Gone.gp4",
    "Sleeping VillageA Bit of Finger.gp4",
    "Snowblind.gp4",
    "Solitude.gp3",
    "Spiral Architect.gp3",
    "St. Vitus Dance.gp3",
    "Supernaut.gp4",
    "Sweet Leaf.gp3",
    "Symptom Of The Universe.gp5",
    "The Eternal Idol.gp4",
    "The Illusion Of Power.gp4",
    "The Sign Of The Southern Cross.gp4",
    "The Spell.gp4",
    "The Wizard.gp3",
    "Time is Mine.gp3",
    "Time Machine.gp3",
    "Tomorrow's Dream.gp3",
    "Too Late.gp4",
    "Turn To Stone.gp3",
    "Virtual Death.gp4",
    "Voodoo.gp3",
    "War Pigs.gp3",
    "Wicked World.gp3",
    "Zero The Hero.gp4"
  ] },
  { band: "Bon Jovi", tabs: [
    "99 In The Shade.gp4",
    "All About Loving You.gp4",
    "All I Want Is Everything.gp4",
    "Always Run To You.gp4",
    "Always.gp3",
    "Another Reason To Believe.gp4",
    "Bad Medicine.gp4",
    "Bed Of Roses.gp4",
    "Bitter Wine.gp3",
    "Blaze Of Glory.gp3",
    "Blood Money.gp4",
    "Blood On Blood.gp4",
    "Born to be my Baby.gp3",
    "Bounce.gp4",
    "Breakout.gp4",
    "Burning For Love.gp4",
    "Captain Crash & The Beauty Queen From Mars.gp3",
    "Damned.gp4",
    "Diamond Ring.gp4",
    "Dry County.gp4",
    "Edge Of A Broken Heart.gp4",
    "Everyday.gp3",
    "Get Ready.gp4",
    "Good Guys Don't Always Wear White.gp4",
    "Hardest Part Is The Night.gp4",
    "Have A Nice Day.gp4",
    "Hearts Breaking Even.gp4",
    "Hey God.gp4",
    "Homebound Train.gp4",
    "Hook Me Up.gp4",
    "I Believe.gp4",
    "I Want You.gp4",
    "I'll Be There For You.gp3",
    "I'll Sleep When I'm Dead.gp4",
    "Id Die For You.gp4",
    "If I Was Your Mother.gp3",
    "In And Out Of Love.gp4",
    "In These Arms.gp4",
    "It's My Life.gp3",
    "Janie, Don't You Take Your Love To Town.gp4",
    "Joey.gp4",
    "Just Older.gp4",
    "Keep the Faith.gp3",
    "Lay Your Hands On Me.gp4",
    "Let It Rock.gp4",
    "Letting You Go.gp3",
    "Lie To Me.gp3",
    "Livin On A Prayer.gp4",
    "Living In Sin.gp4",
    "Love Me Back To Life.gp4",
    "Misunderstood.gp4",
    "My Guitar Lies Bleeding In My Arms.gp4",
    "Never Say Goodbye.gp4",
    "Next One Hundred Years.gp3",
    "One Wild Night.gp3",
    "Only Lonely.gp4",
    "Open All Night.gp4",
    "Price Of Love.gp4",
    "Raise Your Hands.gp4",
    "Ride Cowboy Ride.gp4",
    "Roulette.gp4",
    "Runaway.gp3",
    "Save The World.gp3",
    "Say It Isn't So.gp4",
    "Secret Dreams.gp4",
    "She Don't Know Me.gp4",
    "Shot Through The Heart.gp4",
    "Silent Night.gp4",
    "Social Disease.gp4",
    "Someday I'll Be Saturday Night.gp3",
    "Something For The Pain.gp3",
    "Something To Believe In.gp4",
    "Stick To Your Guns.gp4",
    "The Distance.gp4",
    "The King Of The Mountain.gp4",
    "These Days.gp4",
    "This Ain't A Love Song.gp3",
    "To The Fire.gp4",
    "Tokyo Road.gp4",
    "Two story town.gp3",
    "Unbreakable.gp4",
    "Undivided.gp4",
    "Wanted Dead Or Alive.gp4",
    "We Rule The Night.gp4",
    "Welcome To Wherever You Are.gp4",
    "Why Aren't You Dead.gp4",
    "Wild In The Streets.gp4",
    "Wild Is The Wind.gp4",
    "Without Love.gp4",
    "Woman In Love.gp4",
    "You Give Love A Bad Name.gp3",
    "You Had Me From Hello.gp4"
  ] },
  { band: "Bush", tabs: [
    "Bomb.gp4",
    "Chemicals Between Us.gp3",
    "Cold Contagious.gp4",
    "Come Down.gp4",
    "Comedown.gp3",
    "Every Thing Zen.gp3",
    "Glycerine.gp3",
    "Greedy Fly.gp3",
    "Letting The Cables Sleep.gp4",
    "Little Things.gp4",
    "Machinehead.gp4",
    "People That We Love.gp4",
    "Swallowed.gp3",
    "The Chemical Between Us.gp3"
  ] },
  { band: "Cheap Trick", tabs: [
    "Clock Strikes Ten.gp4",
    "I Want You To Want Me.gp4",
    "Surrender.gp3",
    "The Flame.gp4"
  ] },
  { band: "Cinderella", tabs: [
    "Comin' Home.gp3",
    "Don't Know What You Got.gp3",
    "Fallin' Apart At The Seams.gp4",
    "Gypsy Road.gp3",
    "Heartbreak Station.gp4",
    "Long Cold Winter.gp3",
    "Nobody's Fool.gp3",
    "Push, Push.gp3",
    "Shake Me.gp3",
    "Somebody Save Me.gp4",
    "The Last Mile.gp4"
  ] },
  { band: "Deep Purple", tabs: [
    "A Gipsy's Kiss.gp4",
    "Anthem.gp3",
    "Any Fule Know That.gp3",
    "Anya.gp4",
    "Anyone's Daughter.gp4",
    "April.gp4",
    "Bad Attitude.gp3",
    "Black & White.gp4",
    "Black Night.gp3",
    "Blind.gp4",
    "Bloodsucker.gp4",
    "Burn.gp3",
    "Call Of The Wild.gp4",
    "Cascades I'm Not Your Lover.gp3",
    "Child In Time.gp3",
    "Cut Runs Deep.gp3",
    "Demons Eye.gp4",
    "Don't Let Go.gp5",
    "Fireball.gp3",
    "Flight Of The Rat.gp4",
    "Fools.gp4",
    "Gettin' Tighter.gp4",
    "Gypsy's Kiss.gp3",
    "Hallelujah.gp4",
    "Hard Lovin' Woman.gp4",
    "Hard Loving Man.gp4",
    "Haunted.gp4",
    "Highway Star.gp3",
    "Holy Man.gp4",
    "House Of Pain.gp4",
    "Hungry Daze.gp4",
    "Hush.gp4",
    "I'm Alone.gp3",
    "Into The Fire.gp4",
    "Kentucky Woman.gp3",
    "Knocking At Your Back Door.gp3",
    "Lady Double Dealer.gp4",
    "Lalena.gp4",
    "Lay Down, Stay Down.gp3",
    "Lazy.gp4",
    "Living Wreck.gp4",
    "Love Child.gp4",
    "Love Conquers All.gp3",
    "Mad Dog.gp4",
    "Mary Long.gp4",
    "Maybe I'm A Leo.gp3",
    "Mean Streak.gp4",
    "Mistreated.gp4",
    "Never A Word.gp3",
    "Never Before.gp4",
    "No No No.gp4",
    "No One Came.gp4",
    "Nobody's Home.gp3",
    "Perfect Strangers.gp3",
    "Pictures Of Home.gp4",
    "Rat Bat Blue.gp3",
    "Sail Away.gp4",
    "Smoke On The Water.gp3",
    "Smooth Dancer.gp4",
    "Soldier Of Fortune.gp4",
    "Somebody Stole My Guitar.gp4",
    "Sometimes I Feel Like Screaming.gp4",
    "Space Truckin'.gp3",
    "Speed King.gp4",
    "Stormbringer.gp4",
    "Strange Kind of Woman.gp3",
    "Super Trouper.gp4",
    "The Battle Rages On.gp4",
    "The Gypsy.gp4",
    "The Mule.gp4",
    "The Purpendicular Waltz.gp4",
    "The Spanish Archer.gp3",
    "The Well Dressed Guitar.gp4",
    "Under The Gun.gp4",
    "Unwritten Law.gp3",
    "Vavoom Ted The Mechanic.gp4",
    "Wasted Sunsets.gp4",
    "What's Going On Here.gp4",
    "When A Blind Man Cries.gp3",
    "Woman From Tokyo.gp4",
    "Wring That Neck.gp3",
    "You Can't Do It Right.gp3",
    "You Fool No One.gp4"
  ] },
  { band: "Def Leppard", tabs: [
    "Action! Not Words.gp4",
    "Animal.gp4",
    "Armageddon.gp3",
    "Bringin' On The Heartbreak.gp4",
    "Die Hard The Hunter.gp4",
    "Don't Shoot Shot Gun.gp4",
    "Foolin'.gp4",
    "Gods Of War.gp4",
    "Have You Ever Needed Someone So Bad.gp4",
    "Heaven Is.gp4",
    "Hysteria.gp4",
    "I Wanna Touch U.gp4",
    "Love And Affection.gp4",
    "Love Bites.gp3",
    "Miss You In A Heartbeat.gp4",
    "Photograph.gp4",
    "Pour Some Sugar On Me.gp4",
    "Promises.gp3",
    "Pyromania.gp4",
    "Ring of Fire.gp3",
    "Rock Of Ages.gp4",
    "Rock Rock.gp4",
    "Rocket.gp4",
    "Run Riot.gp4",
    "Stagefright.gp4",
    "Switch 625.gp4",
    "Tear It Down.gp4",
    "Tonight.gp4",
    "Too Late For Love.gp4",
    "Two Steps Behind.gp3",
    "When Love and Hate Collide.gp3",
    "Women.gp4"
  ] },
  { band: "Deftones", tabs: [
    "7 Words.gp3",
    "Anniversary Of An Uninteresting Event.gp4",
    "Around the Fur.gp3",
    "Back To School.gp3",
    "Battle-axe.gp4",
    "Be Quiet and Drive.gp3",
    "Birthmark.gp3",
    "Bloody Cape.gp4",
    "Bored.gp3",
    "Change.gp3",
    "Chauffeur.gp3",
    "Damone.gp3",
    "Deathblow.gp4",
    "Digital Bath.gp3",
    "Elite.gp3",
    "Engine 9.gp3",
    "Engine Number 9.gp3",
    "Feiticiera.gp3",
    "Good Morning Beautiful.gp4",
    "Hexagram.gp4",
    "If Only Tonight We Could Sleep.gp4",
    "Knife Party.gp3",
    "Korea.gp3",
    "Lhabia.gp3",
    "Lifter.gp3",
    "Mascara.gp3",
    "Minerva.gp4",
    "Minus Blindfold.gp3",
    "Mx.gp3",
    "My Own Summer.gp4",
    "Needles And Pins.gp3",
    "Nosebleed.gp3",
    "One Weak.gp4",
    "Passenger.gp3",
    "Pink Maggit.gp3",
    "Pretty Lush.gp3",
    "Rickets.gp3",
    "Root.gp3",
    "Rx queen.gp3",
    "Street Carp.gp3",
    "The Boy's Republic.gp3",
    "When Girls Telephone Boys.gp3"
  ] },
  { band: "Dio", tabs: [
    "All The Fools Sailed Away.gp4",
    "As Long As It's Not About Love.gp3",
    "Between Two Hearts.gp3",
    "Born On The Sun.gp4",
    "Breathless.gp4",
    "Bring Down The Rain.gp3",
    "Caught In The Middle.gp3",
    "Challis.gp4",
    "Don't Talk To Strangers.gp3",
    "Dream Evil.gp4",
    "Egypt.gp4",
    "Evil Eyes.gp3",
    "Fever Dreams.gp4",
    "Hey Angel.gp4",
    "Holy Diver.gp3",
    "Hungry For Heaven.gp3",
    "I Could Have Been A Dreamer.gp3",
    "I Speed At Night.gp3",
    "Invisible.gp4",
    "Killing The Dragon.gp4",
    "King Of Rock'n Roll.gp4",
    "Lord Of The Last Day.gp3",
    "Lost My Insanity.gp4",
    "Mystery.gp4",
    "Naked In The Rain.gp3",
    "Night People.gp4",
    "One More For The Road.gp5",
    "One Night In The City.gp4",
    "Rainbow In The Dark.gp4",
    "Sacred Heart.gp3",
    "Scream.gp4",
    "Shame On The Night.gp4",
    "Shivers.gp4",
    "Stand Up And Shout.gp3",
    "Straight Through The Heart.gp4",
    "Sunset Superman.gp3",
    "The Last In Line.gp3",
    "This Is Your Life.gp3",
    "We Rock.gp4",
    "Wild One.gp3"
  ] },
  { band: "Doctor Feelgood", tabs: [
    "Looking Back.gp4",
    "Milk And Alcohol.gp4"
  ] },
  { band: "Dokken", tabs: [
    "Alone Again.gp3",
    "Breaking The Chains.gp3",
    "Dream Warriors.gp3",
    "In My Dreams.gp3",
    "Into The Fire.gp4",
    "Jaded Heart.gp4",
    "Just Got Lucky.gp4",
    "Mr. Scary.gp4",
    "Standing In The Shadows.gp4",
    "Unchain The Night.gp3"
  ] },
  { band: "Europe", tabs: [
    "Carrie.gp4",
    "Cherokee.gp3",
    "Got To Have Faith.gp3",
    "Halfway To Heaven.gp3",
    "Heart Of Stone.gp4",
    "I'll Cry For You.gp3",
    "In The Future To Come.gp4",
    "Love Chaser.gp4",
    "On The Loose.gp4",
    "Open Your Heart.gp3",
    "Prisoners In Paradise.gp3",
    "Ready Or Not.gp4",
    "Rock the Night.gp3",
    "Scream of Anger.gp3",
    "Seven Doors Hotel.gp4",
    "Sign Of The Times.gp3",
    "Stormwind.gp3",
    "Superstitius solo complete.gp3",
    "superstitius.gp3",
    "The Final Countdown.gp4",
    "Time Has Come.gp4"
  ] },
  { band: "Exodus", tabs: [
    "A Lesson In Violence.gp3",
    "And Then There Were None.gp3",
    "Bonded By Blood.gp4",
    "Deliver Us To Evil.gp3",
    "Impaler.gp4",
    "Karma's Messenger.gp4",
    "Like Father, Like Son.gp4",
    "Metal Command.gp3",
    "No Love.gp3",
    "Piranha.gp4",
    "Scar Spangled Banner.gp4",
    "Shroud Of Urine.gp4",
    "Toxic Waltz.gp3",
    "War Is My Shepard.gp4"
  ] },
  { band: "Extreme", tabs: [
    "Am I Ever Gonna Change.gp3",
    "Big Boys Don't Cry.gp4",
    "Cupid's dead.gp4",
    "Cynical.gp3",
    "Decadence Dance.gp4",
    "Get the Funk Out.gp3",
    "He-man Women Hater.gp4",
    "Hip Today.gp4",
    "Hole Hearted.gp3",
    "Hole in my heart.gp3",
    "It's A Monster.gp4",
    "Kid Ego.gp4",
    "Little Girls.gp4",
    "Midnight Express.gp3",
    "Money.gp3",
    "More Than Words.gp3",
    "more than words.gp3",
    "Mucha.gp3",
    "Nuno Lesson.gp3",
    "Our Father.gp4",
    "Peacemaker Die.gp3",
    "Play That Funky Music.gp4",
    "Play With Me.gp3",
    "Politicalamity.gp4",
    "Pornograffitti.gp3",
    "Rest In Peace.gp3",
    "Rise 'n Shine.gp4",
    "Song For Love.gp4",
    "Stop The World.gp3",
    "Suzie.gp3",
    "Teacher's Pet.gp4",
    "There Is No God.gp3",
    "Tragic Comic.gp3",
    "Warheads.gp4",
    "When I'm President.gp3"
  ] },
  { band: "Faith No More", tabs: [
    "A Small Victory.gp4",
    "Ashes To Ashes.gp4",
    "Caffeine.gp3",
    "Caralho Voador.gp4",
    "Collision.gp3",
    "Crack Hitler.gp3",
    "Cuckoo for Caca.gp3",
    "Digging the Grave.gp3",
    "Diggrave.gp3",
    "Easy.gp3",
    "Edge of the World.gp3",
    "Epic.gp3",
    "Everything's Ruined.gp4",
    "Evidence.gp3",
    "Falling To Pieces.gp3",
    "From Out Of Nowhere.gp3",
    "Gentle Art of Making Enemies.gp3",
    "Get Out.gp3",
    "Helpless.gp3",
    "Home Sick Home.gp4",
    "Jim.gp3",
    "Jizzlober.gp3",
    "Kindergarten.gp4",
    "King for a Day.gp3",
    "Land of Sunshine.gp3",
    "Last Cup Of Sorrow.gp4",
    "Malpractice.gp3",
    "Midlife Crisis.gp4",
    "Midnight Cowboy.gp4",
    "Naked In Front Of The Computer.gp4",
    "Ricochet.gp3",
    "RV.gp4",
    "Smaller and Smaller.gp3",
    "Stripsearch.gp3",
    "Surprise! Your Dead!.gp3",
    "Take This Bottle.gp4",
    "The Last to Know.gp3",
    "The Morning After.gp3",
    "The Real Thing.gp3",
    "Underwater Love.gp3",
    "War Pigs.gp3",
    "We Care A Lot.gp4",
    "Woodpecker From Mars.gp3",
    "Zombie Eaters.gp3"
  ] },
  { band: "Genesis", tabs: [
    "Abacab.gp3",
    "After The Ordeal.gp4",
    "Afterglow.gp3",
    "Back In N.Y.C..gp3",
    "Blood On The Rooftops.gp3",
    "Carpet Crawlers.gp4",
    "Cuckoo Cocoon.gp4",
    "Dance On A Volcano.gp3",
    "Entangled.gp4",
    "Firth Of Fifth.gp3",
    "For Absent Friends.gp4",
    "Harlequin.gp4",
    "Horizons.gp3",
    "Horizons.gp4",
    "I Can't Dance.gp4",
    "In The Cage.gp3",
    "Land of Confusion.gp3",
    "Mama.gp3",
    "Supper's Ready.gp3",
    "The Cinema Show.gp3",
    "The Knife.gp4",
    "The Musical Box.gp4"
  ] },
  { band: "Guns N' Roses", tabs: [
    "14 Years.gp4",
    "Ain't It Fun.gp3",
    "Anything Goes.gp4",
    "Attitude.gp4",
    "Back Off Bitch.gp4",
    "Bad Apples.gp3",
    "Bad Obsession.gp4",
    "Breakdown.gp3",
    "Buick Mackane.gp3",
    "Chinese Democracy.gp3",
    "Civil War.gp3",
    "Coma.gp4",
    "Crash Diet.gp3",
    "Dead Horse.gp4",
    "Don't Cry.gp3",
    "Don't Damn Me.gp3",
    "Double Talkin' Jive.gp3",
    "Down on the farm.gp3",
    "Dust In The Wind.gp4",
    "Dust N' Bones.gp4",
    "Estranged.gp3",
    "Garden Of Eden.gp4",
    "Get In The Ring.gp4",
    "Hair Of The Dog.gp4",
    "Intermission.gp4",
    "It's So Easy.gp3",
    "Knockin' On Heaven's Door.gp3",
    "Live And Let Die.gp3",
    "Locomotive.gp3",
    "Madagascar.gp3",
    "Mama Kin.gp4",
    "Move To The City.gp4",
    "Mr. Brownstone.gp4",
    "My Michelle.gp3",
    "New Rose.gp3",
    "Nice Boys.gp4",
    "Nightrain.gp3",
    "November Rain.gp4",
    "Oh My God.gp3",
    "One in a Million.gp3",
    "Out Ta Get Me.gp3",
    "Paradise City.gp3",
    "Patience.gp4",
    "Perfect Crime.gp3",
    "Pretty Tied Up.gp3",
    "Reckless Life.gp4",
    "Right Next Door To Hell.gp4",
    "Rocket Queen.gp4",
    "Shotgun Blues.gp4",
    "Since I Don't Have You.gp4",
    "So Fine.gp3",
    "Spanish Guitar.gp4",
    "Sweet Child O' Mine.gp4",
    "The Garden.gp3",
    "Think About You.gp4",
    "Used To Love Her.gp3",
    "Welcome To The Jungle.gp4",
    "Wild Horses.gp4",
    "Yesterdays.gp3",
    "You Ain't The First.gp3",
    "You Could Be Mine.gp3",
    "You're Crazy.gp4"
  ] },
  { band: "Helloween", tabs: [
    "A Game We Shouldn't Play.gp3",
    "A Little Time.gp3",
    "A Million To One.gp3",
    "A Tale That Wasn't Right.gpx",
    "All My Loving.gp4",
    "All Over The Nations.gp4",
    "Anything My Mama Don't Like.gp3",
    "Before The War.gp3",
    "Cry For Freedom.gp3",
    "Don't Spit On My Mind.gp3",
    "Eagle Fly Free.gp3",
    "Falling Higher.gp3",
    "First Time.gp3",
    "Follow The Sign.gp4",
    "Forever And One.gp3",
    "Future World.gp3",
    "Gorgar.gp3",
    "Guardians.gp4",
    "Halloween.gp4",
    "Heavy Metal.gp3",
    "Hell Was Made In Heaven.gp3",
    "Hey Lord!.gp3",
    "How Many Tears.gp3",
    "I Can.gp3",
    "I Live For Your Pain.gp3",
    "I Want Out.gp3",
    "I'm Alive.gp4",
    "If I Could Fly.gp3",
    "In The Middle Of A Heartbeat.gp4",
    "Judas.gp4",
    "Just a Little Sign.gp4",
    "Keeper Of The Seven Keys.gp3",
    "Kings Will Be Kings.gp3",
    "Laudate Dominum.gp3",
    "Mankind.gp4",
    "March Of Time.gp4",
    "Midnight Sun.gp3",
    "Mirror Mirror.gp4",
    "Mission Motherland.gp4",
    "Mr. Torture.gp4",
    "Mrs. God.gp4",
    "Murderer.gp3",
    "Never Be A Star.gp4",
    "Open Your Life.gp4",
    "Oriental Journey.gp4",
    "Perfect Gentleman.gp4",
    "Phantoms Of Death.gp4",
    "Pleasure Drone.gp5",
    "Power.gp3",
    "Push.gp3",
    "Reptile.gp3",
    "Revelation.gp3",
    "Ride The Sky.gp4",
    "Rise And Fall.gp3",
    "Salvation.gp4",
    "Savage.gp3",
    "Save Us.gp3",
    "Secret Alibi.gp3",
    "Sole Survivor.gp4",
    "Starlight.gp3",
    "Steel Tormentor.gp4",
    "Still We Go.gp3",
    "Take Me Home.gp3",
    "The Chance.gp3",
    "The Dark Ride.gp3",
    "The Departed.gp4",
    "The Game Is On.gp4",
    "The Time Of The Oath.gp3",
    "Time.gp3",
    "Twilight Of The Gods.gp3",
    "Victim Of Fate.gp3",
    "Wake Up The Mountain.gp3",
    "Warrior.gp4",
    "We Burn.gp3",
    "We Got The Right.gp3",
    "Where The Rain Grows.gp4",
    "Why.gp3",
    "Windmill.gp3",
    "You Always Walk Alone.gp3"
  ] },
  { band: "Iron Maiden", tabs: [
    "2 Minutes To Midnight.gp4",
    "22 Acacia Avenue.gp3",
    "Aces High.gp3",
    "Afraid To Shoot Strangers.gp3",
    "Alexander the Great.gp3",
    "Back in the Village.gp3",
    "Be Quick or Be Dead.gp3",
    "Blood Brothers.gp3",
    "Blood On the World's Hand.gp3",
    "Brave New World.gp3",
    "Burning Ambition.gp3",
    "Can I Play with Madness.gp3",
    "Caught Somewhere In Time.gp3",
    "Charlotte The Harlot.gp3",
    "Children Of The Damned.gp3",
    "Como Estais Amigo.gp3",
    "Cross Eyed Mary.gp3",
    "Deja Vu.gp3",
    "Die With Your Boots On.gp3",
    "Don't Look To The Eyes Of The Stranger.gp3",
    "Dream Of Mirrors.gp3",
    "Fear Is the Key.gp3",
    "Fear Of The Dark.gp3",
    "Flash of the blade.gp3",
    "Flight Of Icarus.gp3",
    "Fortunes Of War.gp3",
    "From Here To Eternity.gp3",
    "Futureal.gp3",
    "Gangland.gp3",
    "Ghost Of Navigator.gp3",
    "Hallowed By The Name.gp3",
    "Heaven Can Wait.gp3",
    "Holy Smoke.gp3",
    "Infinite Dreams.gp3",
    "Innocent Exile.gp3",
    "Invaders.gp3",
    "Invasion.gp3",
    "Iron Maiden.gp3",
    "Judas Be My Guide.gp3",
    "Kill Me Ce Soir.gp3",
    "Killers.gp3",
    "Lightning strike twice.gp3",
    "Look For The Truth.gp3",
    "Lord Of The Flies.gp3",
    "Losfer Words.gp3",
    "Man On the Edge.gp3",
    "Moonchild.gp3",
    "Murders In The Rue Morgue.gp3",
    "My Generation.gp3",
    "No Prayer For the Dying.gp3",
    "Only the Good Die Young.gp3",
    "Out of the silent planet.gp3",
    "Phantom Of the Opera.gp3",
    "Posso Te Esperar.gp3",
    "Powerslave.gp3",
    "Prowler.gp3",
    "Purgatory.gp3",
    "Quest For Fire.gp3",
    "Remember Tomorrow.gp3",
    "Revelations.gp3",
    "Rime of the Ancient Mariner.gp3",
    "Run to the Hills.gp3",
    "Running Free.gp3",
    "Sanctuary.gp3",
    "Sea Of Madness.gp3",
    "Seventh Son Of A Seventh Son.gp3",
    "Sign Of the Cross.gp3",
    "Son Of A Gun.gp3",
    "Stanger in a Strange Land.gp3",
    "Still Life.gp3",
    "Sun And Steel.gp3",
    "The Aftermath.gp3",
    "The Assassin.gp3",
    "The Clairvoyant.gp3",
    "The Clansman.gp3",
    "The Duellists.gp3",
    "The Edge Of Darkness.gp3",
    "The Evil That Men Do.gp3",
    "The Fugitive.gp3",
    "The Ides Of March.gp3",
    "the nomad.gp3",
    "The Number Of the Beast.gp3",
    "The Prisoner.gp3",
    "The Prophecy.gp3",
    "The Thin Line Between Love And Hate.gp3",
    "The Trooper.gp3",
    "The Unbeliever.gp3",
    "The Wicker Man.gp3",
    "To Tame A Land.gp3",
    "Total Eclipse.gp3",
    "Transylvania.gp3",
    "Twilight Zone.gp3",
    "Virus.gp3",
    "Wasted Years.gp3",
    "Wasting Love.gp3",
    "Weekend Warrior.gp3",
    "When Two Worlds Collide.gp3",
    "Where Eagles Dare.gp3",
    "Women In Uniform.gp3",
    "Wrathchild.gp3"
  ] },
  { band: "Jethro Tull", tabs: [
    "A New Day Yesterday.gp4",
    "A Song For Jeffery.gp4",
    "Acres Wild.gp4",
    "Aqualung.gp3",
    "Bungle In The Jungle.gp4",
    "Cheap Day Return.gp4",
    "Christmas Song.gp4",
    "Cross-Eyed Mary.gp4",
    "Elegy.gp3",
    "Far Alaska.gp4",
    "Farm On The Freeway.gp4",
    "For A Thousand Mothers.gp4",
    "Living in the past.gp3",
    "Locomotive Breath.gp4",
    "Minstrel In The Gallery.gp3",
    "Mother Goose.gp4",
    "Nothing To Say.gp4",
    "Only Solitaire.gp4",
    "Requiem.gp4",
    "The Chequered Flag.gp4",
    "The Third Hoorah.gp4",
    "Thick As a Brick.gp3",
    "To Cry You A Song.gp4",
    "Too Old To Rock 'N' Roll, Too Young To Die.gp4",
    "We Used To Know.gp4",
    "Wondering Aloud.gp4"
  ] },
  { band: "Judas Priest", tabs: [
    "A Touch Of Evil.gp3",
    "All Guns Blazing.gp4",
    "Angel.gp4",
    "Battle Hymn.gp4",
    "Before the dawn.gp3",
    "Between The Hammer And The Anvil.gp4",
    "Beyond The Realms Of Death.gp4",
    "Blood Red Sky.gp4",
    "Bloodstone.gp4",
    "Breaking The Law.gp3",
    "Bullet Train.gp4",
    "Burn In Hell.gp4",
    "Death Row.gp4",
    "Desert Plains.gp4",
    "Diamonds And Rust.gp4",
    "Don`t Go.gp4",
    "Dreamer Deceiver.gp4",
    "Electric Eye.gp4",
    "Eulogy.gp4",
    "Exciter.gp4",
    "Freewheel Burning.gp4",
    "Grinder.gp3",
    "Hard As Iron.gp4",
    "Heading Out To The Highway.gp4",
    "Heavy Duty.gp3",
    "Heavy Metal.gp4",
    "Hell Bent For Leather.gp4",
    "Hell Patrol.gp3",
    "Hellrider.gp4",
    "I'm A Rocker.gp3",
    "Jawbreaker.gp4",
    "Johnny B. Goode.gp4",
    "Judas Rising.gp4",
    "Jugulator.gp4",
    "Leather Rebel.gp4",
    "Living After Midnight.gp3",
    "Locked In.gp3",
    "Lost And Found.gp4",
    "Metal Gods.gp4",
    "Metal Meltdown.gp4",
    "Monsters Of Rock.gp4",
    "Night Comes Down.gp3",
    "Nightcrawler.gp3",
    "One Shot At Glory.gp4",
    "Out In The Cold.gp4",
    "Painkiller.gp3",
    "Private Property.gp4",
    "Ram It Down.gp3",
    "Reckless.gp4",
    "Revolution.gp4",
    "Riding On The Wind.gp4",
    "Rock Hard Ride Free.gp4",
    "Rock You All Around The World.gp3",
    "Run Of The Mill.gp4",
    "Running Wild.gp3",
    "Savage.gp4",
    "Screaming for Vengeance.gp3",
    "Sinner.gp4",
    "Some Heads Are Gonna Roll.gp4",
    "Stained Class.gp4",
    "Take On The World.gp4",
    "The Green Manalishi.gp3",
    "The Hellion.gp3",
    "The Rage.gp4",
    "The Ripper.gp4",
    "The Sentinel.gp3",
    "Touch Of Evil.gp4",
    "Turbo Lover.gp3",
    "Tyrant.gp3",
    "United.gp3",
    "Victim Of Changes.gp4",
    "What's My Name.gp4",
    "Worth Fighting For.gp4",
    "You've Got Another Thing Comin'.gp4"
  ] },
  { band: "Kiss", tabs: [
    "100,000 years.gp3",
    "2.000 Man.gp3",
    "All American Man.gp3",
    "Almost Human.gp3",
    "And On The 8th Day.gp3",
    "Anything For My Baby.gp3",
    "Beth.gp4",
    "Black Diamond.gp3",
    "C'mon and Love Me.gp3",
    "Calling Dr. Love.gp3",
    "Carr Jam 1981.gp4",
    "Charisma.gp3",
    "Christine Sixteen.gp3",
    "Cold Gin.gp3",
    "Comin' Home.gp3",
    "Crazy Crazy Nights.gp4",
    "Creatures of the Night.gp3",
    "Detroit Rock City.gp3",
    "Deuce.gp3",
    "Do You Love Me.gp3",
    "Domino.gp3",
    "Escape From The Island.gp4",
    "Every Time I Look At You.gp3",
    "Firehouse.gp4",
    "Forever.gp4",
    "Getaway.gp3",
    "God Gave Rock N Roll To You II.gp4",
    "God of Thunder.gp3",
    "Got Love For Sale.gp4",
    "Got To Choose.gp4",
    "Hard Luck Woman.gp3",
    "Hate.gp3",
    "Heart Of Chrome.gp4",
    "Heavens on Fire.gp3",
    "Hotter Than Hell.gp3",
    "I Just Wanna.gp4",
    "I Love It Loud.gp3",
    "I love It Loud.gp3",
    "I Pledge Allegiance To the State of Rock and Roll.gp3",
    "I Still Love You.gp3",
    "I Stole Your Love.gp3",
    "I Want It Loud.gp4",
    "I Was Made For Lovin' You.gp3",
    "I Will Be There.gp3",
    "In The Mirror.gp3",
    "Journey of 1000 Years.gp3",
    "Just A Boy.gp4",
    "Killer.gp3",
    "King Of The Mountain.gp3",
    "Ladies Room.gp3",
    "Let Me Go Rock 'n Roll.gp3",
    "Let Me Know.gp3",
    "Let's Put the X in Sex.gp3",
    "Lick It Up.gp3",
    "Love Gun.gp3",
    "Love Her All I Can.gp3",
    "Love In Chains.gp4",
    "Makin' Love.gp3",
    "Master And Slave.gp3",
    "Mr Speed.gp3",
    "Nothin' To Lose.gp3",
    "Nothing Can Keep Me From You.gp3",
    "Only You.gp3",
    "Parasite.gp3",
    "Partners In Crime.gp3",
    "Plaster Caster.gp3",
    "Psycho Circus.gp3",
    "Raise Your Glasses.gp3",
    "Reason To Live.gp3",
    "Reason To Live.gp4",
    "Rip it out.gp3",
    "Rock And Roll Hell.gp3",
    "Rock Bottom.gp3",
    "Rock Hard.gp3",
    "Rocket Ride.gp3",
    "Shandi.gp4",
    "She.gp3",
    "Shock Me.gp3",
    "Shout It Loud.gp4",
    "Spit.gp4",
    "Strutter.gp3",
    "Sure Know Something.gp3",
    "Take It Off.gp4",
    "Talk To Me.gp3",
    "Tears Are Falling.gp4",
    "Thou Shalt Not.gp4",
    "Thrills In The Night.gp4",
    "Tough Love.gp4",
    "True Confessions.gp3",
    "Two Timer.gp3",
    "Under The Rose.gp4",
    "Unholy.gp3",
    "War Machine.gp3",
    "Watchin' You.gp3",
    "We Are One.gp3",
    "Who Wants To Be Lonely.gp3"
  ] },
  { band: "Krokus", tabs: [
    "Headhunter.gp3",
    "Rock City.gp3"
  ] },
  { band: "Led Zeppelin", tabs: [
    "Absolution Blues.gp3",
    "achilles last stand.gp3",
    "Achilles Last Stand.gp4",
    "All My Love.gp3",
    "As Long As I Have You.gp4",
    "Babe, I'm Gonna Leave You.gp4",
    "Black Country woman.gp4",
    "Black Dog.gp3",
    "Black Mountain Side.gp3",
    "Boogie With Stu.gp3",
    "Braun Yr Aur.gp3",
    "Bring It On Home.gp3",
    "Bron-Y-Aur Stomp.gp3",
    "Candy Store Rock.gp3",
    "Celebration Day.gp3",
    "Communication Breakdown.gp4",
    "Custard pie.gp3",
    "D'yer Mak'er.gp3",
    "Dancing Days.gp3",
    "Darlene.gp4",
    "Dazed And Confused.gp4",
    "Down By The Seaside.gp4",
    "For Your Life.gp3",
    "Four Sticks.gp3",
    "Friends.gp4",
    "Gallows Pole.gp3",
    "Going To California.gp3",
    "Good Times Bad Times.gp4",
    "Heartbreaker.gp3",
    "Hey Hey What Can I Do.gp3",
    "Hot Dog.gp4",
    "Houses of the Holy.gp3",
    "How Many More Times.gp4",
    "I Can't Quit You Baby.gp3",
    "Im Gonna Crawl.gp3",
    "Immigrant Song.gp4",
    "In My Time of Dying.gp3",
    "In The Evening.gp3",
    "In The Light.gp3",
    "Kashmir.gp3",
    "Livin' Lovin' Maid.gp4",
    "Living Loving Maid.gp3",
    "Misty Mountain Hop.gp3",
    "Moby Dick.gp3",
    "Night Flight.gp3",
    "No Quarter.gp3",
    "Nobody's Fault But Mine.gp3",
    "Out On The Tiles.gp4",
    "Over The Hills And Far Away.gp4",
    "Ozone Baby.gp4",
    "Poor Tom.gp4",
    "Ramble On.gp3",
    "Rock And Roll.gp4",
    "Royal Orleans.gp3",
    "Sick Again.gp4",
    "Since I've Been Loving You.gp3",
    "South Bound Saurez.gp4",
    "Stairway To Heaven.gp4",
    "Tangerine.gp3",
    "Ten Years Gone.gp3",
    "Thank You.gp3",
    "That's The Way.gp4",
    "The Battle Of Evermore.gp4",
    "The Girl I Love She Got Long Black Wavy Hair.gp3",
    "The Lemon Song.gp3",
    "The Ocean.gp4",
    "The Rain Song.gp4",
    "The Rover.gp3",
    "The Song Remains The Same.gp3",
    "The Wanton Song.gp3",
    "Trampled Under Foot.gp4",
    "Travelling Riverside Blues.gp4",
    "Walters Walk.gp4",
    "Wearing And Tearing.gp4",
    "What Is And What Should Never Be.gp4",
    "When The Levee Breaks.gp3",
    "White Summer-Black Mountainside.gp4",
    "White Summer.gp4",
    "Whole Lotta Love.gp4",
    "You Shook Me.gp4",
    "Your Time Is Gonna Come.gp4"
  ] },
  { band: "Lordi", tabs: [
    "Biomechanic Man.gp4",
    "Blood Red Sandman.gp4",
    "Devil Is A Loser.gp3",
    "Dynamite Tonite.gp4",
    "Hard rock hallelujah.gp5",
    "Hellbender Turbulence.gp4",
    "Icon Of Dominance.gp4",
    "Last Kiss Good Bye.gp4",
    "Rock The Hell Outta You.gp4",
    "Would You Love A Monsterman.gp3"
  ] },
  { band: "Machine Head", tabs: [
    "A Nation On Fire.gp3",
    "A Thousand Lies.gp3",
    "All Falls Down.gp4",
    "All In Your Head.gp4",
    "American High.gp4",
    "Bite The Bullet.gp4",
    "Blistering.gp4",
    "Block.gp4",
    "Blood Of The Zodiac.gp4",
    "Bulldozer.gp4",
    "Crushing Around You.gp3",
    "Davidian.gp3",
    "Days Turn Blue to Gray.gp4",
    "Deafening Silence.gp3",
    "Descend The Shades Of Night.gp4",
    "Down To None.gp4",
    "Elegy.gp4",
    "Exhale The Vile.gp4",
    "From This Day.gp3",
    "Imperium.gp3",
    "Message In A Bottle.gp4",
    "None But My Own.gp3",
    "Only The Names.gp3",
    "Rage To Overcome.gp3",
    "Seasons Wither.gp4",
    "Silver.gp4",
    "Ten Ton Hammer.gp4",
    "The Blood, The Sweat, The Tears.gp3",
    "The Burning Red.gp4",
    "The Rage To Overcome.gp4",
    "Trephination.gp4",
    "Violate.gp4"
  ] },
  { band: "Malmsteen", tabs: [
    "2003.gp4",
    "Aftermath.gp4",
    "Anguish And Fear.gp3",
    "Another Time.gp4",
    "Arpeggios From Hell.gp3",
    "As Above, So Below.gp3",
    "Asylum.gp3",
    "Bad Blood.gp3",
    "Baroque & Roll.gp4",
    "Battlefield.gp4",
    "Bedroom Eyes.gp3",
    "Beethoven's 5th Symphony.gp3",
    "Black Star.gp3",
    "Black Star.gp4",
    "Blitzkrieg.gp3",
    "Blue.gp3",
    "Braveheart.gp3",
    "Broken Glass.gp3",
    "Brothers.gp4",
    "Child In Time.gp4",
    "Cracking The Whip.gp4",
    "Crash And Burn.gp3",
    "Cry No More.gp3",
    "Crying.gp4",
    "Crystal Ball.gp3",
    "Dark Ages.gp3",
    "Deja Vu.gp3",
    "Demon Driver.gp3",
    "Devil In Disguise.gp3",
    "Disciples Of Hell.gp3",
    "Eclipse.gp3",
    "Ejercicios.gp3",
    "Evil Eye.gp3",
    "Far Beyond the Sun.gp3",
    "Faster Than The Speed Of Light.gp3",
    "Faultline.gp4",
    "Fire In The Sky.gp3",
    "Fire.gp3",
    "Flamenco Diablo.gp4",
    "Forever Is A Long Time.gp3",
    "Forever One.gp4",
    "Fugue.gp4",
    "General Hospital.gp3",
    "Gimme Gimme Gimme.gp4",
    "Hangar 18 Area 51.gp3",
    "Heaven Tonight.gp3",
    "Hiroshima Mon Amour.gp3",
    "Hold On.gp3",
    "How Many Miles To Babylon.gp3",
    "I'll See The Light Tonight.gp3",
    "Icarus dream op4.gp3",
    "In The Name Of God.gp4",
    "Iron Clad.gp4",
    "Island In The Sun.gp3",
    "Jet To Jet.gp3",
    "Judas.gp3",
    "Krakatau.gp3",
    "Leonardo.gp3",
    "Levithian.gp4",
    "Liar.gp3",
    "Like An Angel.gp4",
    "Little Savage.gp3",
    "Locked And Loaded.gp4",
    "Magic Mirror.gp3",
    "Majestic Blue.gp4",
    "Making Love.gp4",
    "Masquerade.gp4",
    "Motherless Child.gp3",
    "My Resurrection.gp3",
    "Never Die.gp4",
    "No Love Lost.gp4",
    "Now Your Ships Are Burned.gp3",
    "On The Run Again.gp3",
    "Overture 1383.gp3",
    "Overture 1622.gp3",
    "Perpetual.gp3",
    "Preludium.gp4",
    "Prisoner Of Your Love.gp3",
    "Queen in Love.gp4",
    "Razor Eater.gp4",
    "Requiem.gp4",
    "Riot In The Dungeons.gp3",
    "Rise Up.gp4",
    "Rising Force.gp3",
    "Sarabande.gp3",
    "Save Our Love.gp3",
    "See You In Hell.gp3",
    "Ship Of Fools.gp4",
    "The 7th Sign.gp4",
    "The seventh sign.gp3",
    "The Stand.gp3",
    "Too Young Too Die, Too Drunk To Live.gp3",
    "Treasure From The East.gp4",
    "Trilogy.gp3",
    "Valhalla.gp4",
    "Vengeance.gp3",
    "What Do You Want.gp3",
    "Wield My Sword.gp3"
  ] },
  { band: "Manowar", tabs: [
    "All Men Play On Ten.gp4",
    "Animals.gp4",
    "Army Of The Immortals.gp3",
    "Battle Hymn.gp3",
    "Blood Of My Enemies.gp4",
    "Blood Of The Kings.gp3",
    "Blow Your Speakers.gp4",
    "Brothers Of Metal.gp4",
    "Call To Arms.gp4",
    "Carry On.gp3",
    "Courage.gp4",
    "Defender.gp4",
    "Fight For Freedom.gp3",
    "Fight Until We Die.gp4",
    "Fighting The World.gp3",
    "Gates Of Valhalla.gp4",
    "Gloves Of Metal.gp4",
    "Hail And Kill.gp4",
    "Hail To England.gp3",
    "Hand Of Doom.gp4",
    "Heart Of Steel.gp4",
    "Holy War.gp4",
    "House of Death.gp4",
    "I Believe.gp4",
    "King Of Kings.gp4",
    "King.gp4",
    "Kingdom Come.gp4",
    "Kings Of Metal.gp3",
    "Manowar.gp5",
    "Master Of The Wind.gp3",
    "Metal Warriors.gp4",
    "My Spirit Lives On.gp4",
    "Number 1.gp4",
    "Outlaw.gp4",
    "Pleasure Slave.gp4",
    "Return Of The Warlord.gp4",
    "Ride The Dragons.gp4",
    "Spirit Horse Of The Cherokee.gp4",
    "Swords In The Wind.gp4",
    "The Art Of Ross The Boss.gp4",
    "The Crown And The Ring.gp4",
    "The Gods Made Heavy Metal.gp4",
    "The Power Of Thy Sword.gp4",
    "The Power.gp4",
    "Thor.gp3",
    "Today Is A Good Day To Die.gp4",
    "Violence And Bloodshed.gp4",
    "Warriors Of The World.gp4",
    "Wheels Of Fire.gp3"
  ] },
  { band: "Megadeth", tabs: [
    "1000 Times Goodbye.gp4",
    "99 Ways To Die.gp4",
    "A Secret Place.gp4",
    "A Tout le Monde.gp3",
    "Addicted To Chaos.gp4",
    "Almost Honest.gp3",
    "Anarchy in the U.K..gp3",
    "Angry Again.gp3",
    "Architecture of Aggression.gp3",
    "Ashes In Your Mouth.gp3",
    "Bad Omen.gp4",
    "Black Friday.gp4",
    "Blackmail The Universe.gp4",
    "Blood Of Heroes.gp3",
    "Breadline.gp4",
    "Breakpoint.gp4",
    "Burning Bridges.gp4",
    "Captive Honour.gp4",
    "Chosen Ones.gp3",
    "Countdown For Exctinction.gp3",
    "Crown Of Worms.gp4",
    "Crush 'em.gp4",
    "Devils Island.gp4",
    "Diadems.gp4",
    "Die Dead Enough.gp4",
    "Disconnect.gp4",
    "Dread And The Fugitive Mind.gp4",
    "Ecstasy.gp4",
    "Elysian Fields.gp3",
    "Family Tree.gp4",
    "FFF.gp4",
    "Five Magics.gp3",
    "Forclosure of a dream.gp3",
    "Go To Hell.gp3",
    "Good MourningBlack Friday.gp4",
    "Hanger 18.gp4",
    "High Speed Dirt.gp3",
    "Holy Wars... The Punishment Due.gp4",
    "Hook In Mouth.gp4",
    "I Thought I Knew It All.gp3",
    "I'll Be There.gp4",
    "I'll Get Even.gp4",
    "In My Darkest Hour.gp4",
    "Insomnia.gp4",
    "Into The Lungs Of Hell.gp4",
    "Kick The Chair.gp4",
    "Kill The King.gp4",
    "Killing Is My Business...And Business Is Good!.gp4",
    "Killing Road.gp4",
    "Liar.gp3",
    "Looking Down The Cross.gp4",
    "lucretia.gp3",
    "Lucretia.gp4",
    "Mary Jane.gp3",
    "Mastermind.gp3",
    "Mechanix.gp4",
    "Moto Psycho.gp3",
    "My Last Words.gp4",
    "New World Order.gp4",
    "Paranoid.gp4",
    "Peace Sells... But Whos's Buying.gp4",
    "Poison Was The Cure.gp4",
    "Prince Of Darkness.gp3",
    "Psychotron.gp4",
    "Rattlehead.gp4",
    "Recipe for Hate... Warhorse.gp4",
    "Reckoning Day.gp4",
    "Return To Hangar.gp3",
    "Rust In Peace... Polaris.gp4",
    "Set The World Afire.gp4",
    "Seven.gp4",
    "She Wolf.gp4",
    "Skin 'O My Teeth.gp4",
    "Something That I'm Not.gp4",
    "sweating bullets.gp3",
    "Sweating Bullets.gp4",
    "Symphony Of Destruction.gp4",
    "Take No Prisoners.gp4",
    "Tears In A Vial.gp4",
    "The Conjuring.gp4",
    "The Disintegrators.gp3",
    "The Doctor Is Calling.gp4",
    "The Killing Road.gp3",
    "The Scorpion.gp4",
    "The World Needs A Hero.gp4",
    "These Boots.gp4",
    "This Was My Life.gp3",
    "Time The Beginning and The End.gp3",
    "Tornado Of Souls.gp4",
    "Train of Consequences.gp3",
    "Trust.gp3",
    "Truth Be Told.gp4",
    "Use The Man.gp4",
    "Victory.gp4",
    "Vortex.gp4",
    "Wake Up Dead.gp4",
    "Wanderlust.gp3",
    "When.gp3",
    "Youthanasia.gp3"
  ] },
  { band: "Metallica", tabs: [
    "...And Justice For All.gp4",
    "Ain't My Bitch.gp4",
    "All Within My Hands.gp4",
    "Am I Evil.gp4",
    "Apocalypse Dawn.gp4",
    "Astronomy.gp4",
    "Battery.gp4",
    "Better Than You.gp4",
    "Blackened.gp4",
    "Bleeding Me.gp4",
    "Blitzkrieg.gp4",
    "Call of Ktulu.gp3",
    "Carpe Diem Baby.gp3",
    "Crash Course In Brain Surgery.gp4",
    "Creeping Death.gp4",
    "Cure.gp4",
    "Damage, Inc..gp4",
    "Devil's Dance.gp3",
    "Dirty Window.gp4",
    "Disposable Heroes.gp3",
    "Don't Tread On Me.gp4",
    "Dyers Eve.gp4",
    "Enter Sandman.gp4",
    "Escape.gp4",
    "Eye Of The Beholder.gp4",
    "Fade To Black.gp4",
    "Fight Fire With Fire.gp4",
    "For Whom The Bell Tolls.gp4",
    "Frantic.gp4",
    "Frayed Ends of Sanity.gp3",
    "Fuel.gp4",
    "Harvester Of Sorrow.gp4",
    "Helpless.gp3",
    "Hero Of The Day.gp4",
    "Hit The Lights.gp3",
    "Holier Than Thou.gp4",
    "I Disappear.gp3",
    "It's Electric.gp3",
    "Jump In The Fire.gp4",
    "Killing Time.gp3",
    "King Nothing.gp4",
    "Leper Messiah.gp4",
    "Loverman.gp3",
    "Low Man's Lyric.gp4",
    "Mama Said.gp3",
    "Master Of Puppets.gp4",
    "Mercyful fate.gp3",
    "Metal Militia.gp3",
    "Motorbreath.gp4",
    "My Friend Of Misery.gp4",
    "My World.gp4",
    "No Leaf Clover.gp4",
    "No Remorse.gp3",
    "Nothing Else Matters.gp4",
    "Of Wolf And Man.gp4",
    "One.gp4",
    "Orion.gp4",
    "Overkill.gp3",
    "Phantom Lord.gp3",
    "Prince Charming.gp3",
    "Purify.gp4",
    "Ride The Lightning.gp4",
    "Ronnie.gp4",
    "Sabbra Cadabra.gp3",
    "Sad But True.gp4",
    "Seek And Destroy.gp3",
    "Shoot Me Again.gp4",
    "Slither.gp3",
    "So What.gp4",
    "Some Kind Of Monster.gp4",
    "St. Anger.gp4",
    "Sweet Amber.gp4",
    "The Call Of Ktulu.gp4",
    "The Four Horsemen.gp4",
    "The Frayed Ends Of Sanity.gp4",
    "The God That Failed.gp4",
    "The Memory Remains.gp3",
    "The Outlaw Torn.gp4",
    "The Prince.gp3",
    "The Shortest Straw.gp4",
    "The Small Hours.gp3",
    "The Struggle Within.gp4",
    "The Thing That Should Not Be.gp4",
    "The Unforgiven II.gp3",
    "The Unforgiven.gp3",
    "The Unnamed Feeling.gp4",
    "The Wait.gp3",
    "Thorn Within.gp4",
    "Through The Never.gp4",
    "To Live Is To Die.gp4",
    "Too Late Too Late.gp3",
    "Trapped Under Ice.gp3",
    "Tuesday's Gone.gp3",
    "Turn the Page.gp4",
    "Until It Sleeps.gp3",
    "Wasting My Hate.gp4",
    "Welcome Home.gp4",
    "Where The Wild Things Are.gp4",
    "Wherever I May Roam.gp4",
    "Wiplash.gp3"
  ] },
  { band: "Motley Crue", tabs: [
    "Danger.gp4",
    "Don't Go Away Mad.gp3",
    "Dr. Feelgood.gp3",
    "Girls Girls Girls.gp3",
    "God Bless The Children Of The Beast.gp4",
    "Helter Skelter.gp3",
    "Home Sweet Home.gp4",
    "If I Die Tomorrow.gp4",
    "Kickstart My Heart.gp4",
    "Knock 'Em Dead Kid.gp3",
    "Live Wire.gp4",
    "Looks That Kill.gp4",
    "Louder Than Hell.gp3",
    "Nona.gp4",
    "Piece Of Your Action.gp3",
    "Power To The Music.gp4",
    "Primal Scream.gp3",
    "Raise Your Hands To Rock.gp4",
    "Red Hot.gp3",
    "Shout At The Devil.gp4",
    "Smoke The Sky.gp3",
    "Smokin' In The Boys Room.gp3",
    "Til Death Do Us Part.gp4",
    "To Young to Fall in Love.gp3",
    "Too Fast for Love.gp3",
    "Use It Or Lose It.gp4",
    "Wild Side.gp4",
    "Without You.gp3"
  ] },
  { band: "Nickelback", tabs: [
    "Another Hole In The Head.gp4",
    "Because Of You (2).gp4",
    "Believe Or Not.gp4",
    "Breathe.gp4",
    "Cowboy Hat.gp4",
    "Do This Anymore.gp4",
    "Far Away.gp4",
    "Feelin Way To Damn Good.gp4",
    "Figured You Out (2).gp4",
    "Flat On The Floor.gp4",
    "Fly.gp3",
    "Good Times Gone.gp4",
    "Hangnail.gp4",
    "Hero.gp4",
    "How You Remind Me.gp4",
    "In Front Of Me.gp3",
    "Just For.gp4",
    "Leader of Men (2).gp3",
    "Money Bought.gp4",
    "Never Again.gp3",
    "Never Again.gp4",
    "Not Leavin' Yet.gp4",
    "Old Enough.gp4",
    "Photograph (2).gp4",
    "See You At The Show.gp4",
    "Side Of A Bullet.gp4",
    "Someday (3).gp4",
    "Throw Your Self Away.gp4",
    "Too Bad (4).gp4",
    "Where Do I HIde (2).gp4",
    "Woke Up This Morning (2).gp4",
    "Worthy To Say.gp4",
    "Yanking Out My Heart.gp4"
  ] },
  { band: "Ozzy", tabs: [
    "Bark At The Moon.gp4",
    "Believer.gp4",
    "Bloodbath In Paradise.gp3",
    "Centre Of Eternity.gp4",
    "Children Of The Grave.gp4",
    "Close My Eyes Forever.gp3",
    "Crazy Babies.gp3",
    "Crazy Train.gp3",
    "Desire.gp3",
    "Diary Of A Madman.gp3",
    "Dreamer.gp3",
    "Facing Hell.gp4",
    "Fire In The Sky.gp4",
    "Flying High Again.gp3",
    "Gets Me Through.gp4",
    "Goodbye To Romance.gp4",
    "Hellraiser.gp3",
    "I Don't Know.gp3",
    "I Don't Want To Change The World.gp4",
    "I Just Want You.gp4",
    "Junkie.gp4",
    "Killer Of Giants.gp4",
    "Lightning Strikes.gp3",
    "Little Dolls.gp4",
    "Mama, I'm Coming Home.gp3",
    "Miracle Man.gp3",
    "Mr. Crowley.gp3",
    "Mr. Tinkertrain.gp3",
    "My Jekyll Doesn't Hide.gp3",
    "My Little Man.gp4",
    "Never.gp4",
    "No Bone Movies.gp3",
    "No More Tears.gp3",
    "Now You See It.gp4",
    "Old L.A. Tonight.gp3",
    "Over The Mountain.gp4",
    "Papa Don't Preach.gp3",
    "Paranoid.gp4",
    "Perry Mason.gp4",
    "Revelation.gp4",
    "Road To Nowhere.gp3",
    "Rock And Roll Rebel.gp3",
    "S.A.T.O..gp3",
    "S.I.N.gp3",
    "See You On The Other Side.gp3",
    "Shot In The Dark.gp4",
    "Slow Down.gp4",
    "Steal Away.gp3",
    "That I Never Had.gp3",
    "The Ultimate Sin.gp4",
    "Time After Time.gp3",
    "Waiting For Darkness.gp4",
    "You Can't Kill Rock And Roll.gp3",
    "You Lookin' At Me Lookin' At You.gp4",
    "You're No Different.gp4"
  ] },
  { band: "Poison", tabs: [
    "Baby Been Around a Bit.gp3",
    "Ball and Chain.gp3",
    "Come Hell or High Water.gp3",
    "Cry Tough.gp4",
    "Doin As I See on My TV.gp3",
    "Don't Give Up An Inch.gp3",
    "Every Rose Has Its Thorn.gp4",
    "Fallen Angel.gp3",
    "Flesh and Blood.gp3",
    "I Won't Forget You.gp4",
    "Let It Play.gp3",
    "Life Goes On.gp4",
    "Life Loves A Tragedy.gp3",
    "Look What The Cat Dragged In.gp4",
    "Nothin' But A Good Time.gp4",
    "Poor Boy Blues.gp3",
    "Richie's Acoustic Thing.gp4",
    "Ride the Wind.gp3",
    "Something To Belive In.gp4",
    "Swampjuice.gp3",
    "Talk Dirty To Me.gp4",
    "Unskinny Bop.gp3",
    "Valley of Lost Souls.gp3"
  ] },
  { band: "Sabaton", tabs: [
    "Metal Machine.gp4",
    "Primo Victoria.gp3"
  ] },
  { band: "Saxon", tabs: [
    "747.gp4",
    "And The Bands Played On.gp4",
    "Broken Heroes.gp4",
    "Crusader.gp4",
    "Denim And Leather.gp4",
    "Dogs Of War.gp4",
    "Killing Ground.gp4",
    "Power And The Glory.gp4",
    "Princess Of The Night.gp4",
    "Strong Arm Of The Law.gp4",
    "The preacher.gp3",
    "We Are Strong.gp4",
    "Wheel Of Steel.gp4"
  ] },
  { band: "Scorpions", tabs: [
    "Alex Truntiagin.gp3",
    "Alien Nation.gp3",
    "Always Somewhere.gp3",
    "always somewhere.gp3",
    "Another Piece Of Meat.gp4",
    "Are You The One.gp3",
    "Belive In Love.gp3",
    "Big City Nights.gp4",
    "Blackout.gp4",
    "Can't Live Without You.gp3",
    "Coming Home.gp4",
    "Does any one know.gp4",
    "Dynamite.gp4",
    "Holiday.gp3",
    "I Can't Explain.gp4",
    "Kicks After Six.gp3",
    "Lady Starlight.gp4",
    "Living For Tomorrow.gp4",
    "Lonely Nights.gp4",
    "Loving You Sunday Morning.gp4",
    "Moment Of Glory.gp4",
    "New Generation.gp4",
    "No One Like You.gp4",
    "No Pain No Gain.gp3",
    "Passion Rules The Game.gp4",
    "Pictured Life.gp3",
    "Polar Nights.gp3",
    "Rhythm Of Love.gp4",
    "Rock You Like a Hurricane.gp3",
    "Sail Of Charon.gp3",
    "Send Me An Angel.gp3",
    "She Said.gp4",
    "Someone To Touch.gp3",
    "Still Loving You.gp3",
    "Tease Me Please Me.gp4",
    "The Zoo.gp4",
    "We'll Burn The Sky.gp4",
    "When The Smoke Is Going Down.gp3",
    "When You Came Into My Life.gp3",
    "White Dove.gp4",
    "Wild Child.gp4",
    "Wind Of Change.gp3",
    "You And I.gp3",
    "You Give Me All I Need.gp4"
  ] },
  { band: "Skid Row", tabs: [
    "18 And Life.gp4",
    "Beggar's day.gp3",
    "Big Guns.gp4",
    "I Remember You.gp3",
    "In A Darkened Room.gp3",
    "Livin' On A Chain Gang.gp4",
    "Monkey Business.gp3",
    "Piece Of Me.gp4",
    "Quicksand Jesus.gp3",
    "Riot Act.gp4",
    "Slave To The Grind.gp4",
    "Sweet little sister.gp3",
    "Thick Is The Skin.gp4",
    "Wasted Time.gp4",
    "Youth Gone Wild.gp4"
  ] },
  { band: "Testament", tabs: [
    "Alone In The Dark.gp4",
    "Apocalyptic City.gp4",
    "Beginning Of The End.gp3",
    "Burnt Offerings.gp3",
    "Curse of the Legions of Death.gp4",
    "D.N.R..gp3",
    "Demonic Refusal.gp3",
    "Disciples Of The Watch.gp4",
    "Dog Faced Gods.gp3",
    "Down For Life.gp3",
    "Eerie Inhabitants.gp3",
    "Electric Crown.gp4",
    "First Strike Is Deadly.gp4",
    "Hail Mary.gp3",
    "Hatred's Rise.gp3",
    "Hypnosis.gp3",
    "Into The Pit.gp4",
    "Legions Of Dead.gp3",
    "Let Go Of My World.gp5",
    "Love To Hate.gp4",
    "Low.gp3",
    "Musical Death.gp3",
    "Over The Wall.gp4",
    "Raging Waters.gp3",
    "Reign Of Terror.gp4",
    "Return To Serenity.gp4",
    "Ride.gp3",
    "Signs Of Chaos.gp3",
    "So Many Lies.gp3",
    "Souls of Black.gp3",
    "The Ballad.gp3",
    "The Burning Times.gp3",
    "The Hauting.gp3",
    "The Legacy.gp3",
    "The New Order.gp4",
    "The Preacher.gp4",
    "Trail Of Tears.gp4",
    "Trial By Fire.gp3",
    "True Believer.gp3",
    "Urotsukidoji.gp3"
  ] },
  { band: "WASP", tabs: [
    "Animal.gp4",
    "Blind In Texas.gp4",
    "Chainsaw Charlie.gp4",
    "Forever Free.gp3",
    "Hellion.gp4",
    "Hold On To My Heart.gp4",
    "I Wanna Be Somebody.gp4",
    "LOVE Machine.gp4",
    "On Your Knees.gp4",
    "Sleeping.gp4",
    "The Idol.gp4",
    "Wild Child.gp4"
  ] },
  { band: "Whitesnake", tabs: [
    "Bad Boys.gp3",
    "Crying In The Rain.gp3",
    "Fool For Your Loving.gp3",
    "Here I Go Again.gp3",
    "Is This Love.gp3",
    "Love Ain't No Stranger.gp3",
    "Now You're Gone.gp3",
    "Sailing Ships.gp3",
    "Slip Of The Tongue.gp3",
    "The Deeper The Love.gp3"
  ] },
  { band: "ZZ Top", tabs: [
    "A Fool For Your Stockings.gp3",
    "Beer Drinkers & Hell Raisers.gp3",
    "Blue Jean Blues.gp3",
    "Cheap Sunglasses.gp4",
    "Doubleback.gp3",
    "Gimme All Your Lovin`.gp3",
    "Give It Up.gp3",
    "Got Me Under Pressure.gp4",
    "I need you tonight.gp4",
    "I Thank You.gp3",
    "I'm Bad, I'm Nationwide.gp3",
    "Jailhouse Rock.gp4",
    "Jesus just left chicago.gp3",
    "Just got paid today.gp3",
    "La Grange.gp3",
    "Legs.gp3",
    "Nasty Dogs & Funky Kings.gp4",
    "Old Man.gp4",
    "Planet Of Women.gp4",
    "Rhythmeen.gp3",
    "Rough Boy.gp4",
    "Sharp Dressed Man.gp4",
    "Stages.gp3",
    "Tube Snake Boogie.gp3",
    "Tush.gp3",
    "Waitin' For The Bus.gp4",
    "World Of Swirl.gp4"
  ] }
];
